apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-web-app
  name: java-web-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: java-web-app
  template:
    metadata:
      labels:
        app: java-web-app
    spec:
      containers:
      - name: my-springboot-app
        image: cnikhilkumar/java-web-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-web-app
    k8s-app: java-web-app
  name: java-web-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: java-web-app
